name: deploy-container

on:
  push:
    branches:
      - master
    paths:
      - "packages/container/**"

defaults:
  run:
    working-directory: packages/container

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - run: npm run build

      - uses: shinyinc/action-aws-cli@v1.2
      - run: aws s3 sync dist s3://${{ secrets.AWS_S3_BUCKET_NAME }}/container/latest
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1


# Anytime that you create a YAML file inside this dot GitHub slash workflows directory and then push that file off to GitHub, GitHub is going to assume that this is some kind
# of workflow that you're going to want to execute at some point in time.
# "packages/container/**"  meaning we only want to run this workflow whenever we make a change specifically to our container project.
# All the different commands that we're going to run in a series of commands we're gonna write out down at the bottom of this file, are all relative
# or should be executed inside the container folder. So we want to specifically run something like say MPM run install or something MPM install, where MPM run build from inside the container directory.
# And as you guess build is going to build and then deploy our project.

# We're gonna reach out to the S3 feature specifically inside that CLI, and we're going to sync our distribution directory that was created when we built our project.
# Remember, whenever we run NPM run build that creates a disc directory